# Generated by Django 4.2.4 on 2023-08-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtMineX', '0003_rename_image_imagecomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecomment',
            old_name='comment',
            new_name='image',
        ),
    ]
