# Generated by Django 4.2.4 on 2023-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtMineX', '0004_rename_comment_imagecomment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
