# Generated by Django 4.2.4 on 2023-08-09 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtMineX', '0008_alter_like_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('image', 'username')},
        ),
    ]
