# Generated by Django 4.2.4 on 2023-08-09 19:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtMineX', '0009_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='images/'),
        ),
    ]
