# Generated by Django 4.2.4 on 2023-08-09 20:08

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ArtMineX', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='images/'),
        ),
    ]
