# Generated by Django 4.2.4 on 2023-08-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtMineX', '0011_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
                ('image', models.ManyToManyField(related_name='image_groups', to='ArtMineX.image')),
                ('members', models.ManyToManyField(blank=True, related_name='member_groups', to=settings.AUTH_USER_MODEL)),
                ('pending_user', models.ManyToManyField(blank=True, related_name='pending_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
