# Generated by Django 4.2.4 on 2023-08-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtMineX', '0014_group_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='pending_user',
            new_name='pending_users',
        ),
    ]
